[project]
name = "game-of-life"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hui Ling Wong" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pydantic",
    "typer",
]

[project.optional-dependencies]
docs = [
    "mkdocs==1.6.1",
    "mkdocs-include-markdown-plugin==7.1.5",
    "mkdocs-jupyter==0.25.1",
    "mkdocs-exclude==1.0.2",
    "mkdocs-material==9.6.12",
    "python-markdown-math==0.9"
]

[dependency-groups]
dev = [
    "prek", # Pre-commit: run `prek install` to add to git config
    "pytest",
    "ruff", # Linter and formatter
    "ty",   # Type checker and language server
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[project.scripts]
game-of-life = "game_of_life.main:app" # Allows CLI to be launched in venv using `game-of-life` command

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"
