name: Publish MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Mkdocs to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v6
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
      - name: Install the project
        run: uv sync --locked --all-groups --extra docs
      - name: Rewrite links in README.md for docs
        env:
          GH_URL: https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}
        run: |
          perl -i -pe '
            s#\]\(docs/([^):]+)\)#](docs/$1)#g;
            s#\]\((?!https?:|mailto:|docs/)([^)]+)\)#]($ENV{GH_URL}/$1)#g
          ' README.md
      - name: Deploy Mkdocs
        run: mkdocs gh-deploy --force
